services:
  playwright:
    container_name: ddev-${DDEV_SITENAME}-playwright
    hostname: ${DDEV_SITENAME}-playwright
    image: ${PLAYWRIGHT_DOCKER_IMAGE:-mcr.microsoft.com/playwright:v1.60.0-noble}
    working_dir: /var/www/html
    command: tail -f /dev/null
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
      - "../:/var/www/html"

  web:
    links:
      - playwright
